// Generated from the dive-analysis workflow — the 10-piece fractal chain.
// Heroes re-derived 2026-07-26 from Higgsfield 4K masters (2560px cap).
window.GAV_CHAIN = [
 {
  "h": "in-our-midst-original-art-on-canvas",
  "t": "In Our Midst",
  "title_html": "In Our <em>Midst</em>",
  "kind": "Original on Canvas",
  "colophon": "Acrylic on canvas &middot; two years in the making",
  "price": 27000,
  "available": true,
  "url": "https://gavinger.com/products/in-our-midst-original-art-on-canvas",
  "img": "media/img/products__IN-OUR-MIDST-WEB_9fc3cd6b-b87b-4639-86e9-ee89e606ca71.webp",
  "w": 2560,
  "cx": 0.37,
  "cy": 0.7,
  "size": 0.18,
  "accent": "#ffc93c",
  "bg": "#150806",
  "line": "Two years distilling the potent energies of a pivotal age into one current.",
  "hpx": 2057
 },
 {
  "h": "midnight-grandfather-clock",
  "t": "Midnight Grandfather Clock",
  "title_html": "<em>Midnight</em> Grandfather Clock",
  "kind": "Funktional Furniture",
  "colophon": "Grandfather clock &middot; custom stained glass &middot; LED",
  "price": 17000,
  "available": true,
  "url": "https://gavinger.com/products/midnight-grandfather-clock",
  "img": "media/img/files__2BFDD372-EA73-4D8C-9A52-015EA17057F2.webp",
  "w": 1653,
  "cx": 0.505,
  "cy": 0.615,
  "size": 0.24,
  "accent": "#b8e34e",
  "bg": "#070a1e",
  "line": "Time bends here. It glows, it waits — this clock marks becoming.",
  "hpx": 2560
 },
 {
  "h": "black-and-white-grandfather-clock",
  "t": "Black & White Grandfather Clock",
  "title_html": "Black &amp; White Grandfather Clock",
  "kind": "Funktional Furniture",
  "colophon": "Posca on stripped grandfather clock &middot; shifting light",
  "price": 12000,
  "available": true,
  "url": "https://gavinger.com/products/black-and-white-grandfather-clock",
  "img": "media/img/files__IMG_8842.webp",
  "w": 1920,
  "cx": 0.51,
  "cy": 0.59,
  "size": 0.17,
  "accent": "#38e3b2",
  "bg": "#060f0d",
  "line": "Stripped to raw wood, reborn line by freehand line; light obeys the button.",
  "hpx": 2560
 },
 {
  "h": "the-transmuter",
  "t": "The Transmuter",
  "title_html": "The <em>Transmuter</em>",
  "kind": "Funktional Furniture",
  "colophon": "Acrylic &amp; paint pen &middot; 75 &times; 36 &times; 20 in &middot; curio clock",
  "price": 12000,
  "available": false,
  "url": "https://gavinger.com/products/the-transmuter",
  "img": "media/img/products__GavinGerundo04_2022_11_web.webp",
  "w": 1706,
  "cx": 0.51,
  "cy": 0.73,
  "size": 0.28,
  "accent": "#ff44a1",
  "bg": "#041008",
  "line": "A grandfather clock reborn in acrylic and paint pen, my largest transmutation yet.",
  "hpx": 2560
 },
 {
  "h": "labyrinth-original-art-on-canvas",
  "t": "Labyrinth",
  "title_html": "<em>Labyrinth</em>",
  "kind": "Original on Canvas",
  "colophon": "Acrylic on canvas",
  "price": 9000,
  "available": false,
  "url": "https://gavinger.com/products/labyrinth-original-art-on-canvas",
  "img": "media/img/products__PILGRIMAGE-WEB.webp",
  "w": 2201,
  "cx": 0.5,
  "cy": 0.38,
  "size": 0.24,
  "accent": "#d63fa0",
  "bg": "#061109",
  "line": "Walk the labyrinth long enough and the path turns vertical, spiraling home to Earth.",
  "hpx": 2560
 },
 {
  "h": "a-moment-of-transparency-original-art-on-canvas",
  "t": "A Moment of Transparency",
  "title_html": "A Moment of <em>Transparency</em>",
  "kind": "Original on Canvas",
  "colophon": "Acrylic on canvas",
  "price": 8500,
  "available": true,
  "url": "https://gavinger.com/products/a-moment-of-transparency-original-art-on-canvas",
  "img": "media/img/products__A-Moment-of-Transparency-WEB_3b5c90f0-26cc-4cd0-8b2e-39f061263354.webp",
  "w": 2560,
  "cx": 0.7,
  "cy": 0.67,
  "size": 0.26,
  "accent": "#4fd9a8",
  "bg": "#0b0814",
  "line": "Painted at a crossroad, in fury and unknowing, until everything became transparent.",
  "hpx": 2560
 },
 {
  "h": "primordial-reverie-framed-original-art-on-canvas",
  "t": "Primordial Reverie",
  "title_html": "Primordial <em>Reverie</em>",
  "kind": "Original on Canvas",
  "colophon": "Acrylic on canvas &middot; 24 &times; 48 in &middot; 2021 &middot; framed",
  "price": 7500,
  "available": false,
  "url": "https://gavinger.com/products/primordial-reverie-framed-original-art-on-canvas",
  "img": "media/img/products__IMG_7101.webp",
  "w": 2032,
  "cx": 0.665,
  "cy": 0.505,
  "size": 0.18,
  "accent": "#ff8c26",
  "bg": "#150705",
  "line": "Born for awe: the cathedrals in the sky reflect the glimmer in your eye.",
  "hpx": 2560
 },
 {
  "h": "curiosity",
  "t": "Curiosity",
  "title_html": "<em>Curiosity</em>",
  "kind": "Funktional Furniture",
  "colophon": "Curio cabinet &middot; music-reactive LED",
  "price": 7000,
  "available": false,
  "url": "https://gavinger.com/products/curiosity",
  "img": "media/img/products__FE5D0DAC-9927-4391-81B5-B3DB74AFA0A0.webp",
  "w": 2560,
  "cx": 0.505,
  "cy": 0.82,
  "size": 0.18,
  "accent": "#35c8f5",
  "bg": "#0a0c1c",
  "line": "A hand-painted vessel, pulsing with sound, built to launch your mind past Mars.",
  "hpx": 2560
 },
 {
  "h": "conquering-carbon-framed-original-art-on-canvas",
  "t": "Conquering Carbon",
  "title_html": "Conquering <em>Carbon</em>",
  "kind": "Original on Canvas",
  "colophon": "Acrylic on canvas &middot; 36 &times; 36 in &middot; framed",
  "price": 6600,
  "available": true,
  "url": "https://gavinger.com/products/conquering-carbon-framed-original-art-on-canvas",
  "img": "media/img/products__CONQUERING-CARBON-WEB_a1620430-9960-4c51-b98a-8e8d6005e1da.webp",
  "w": 2560,
  "cx": 0.5,
  "cy": 0.815,
  "size": 0.2,
  "accent": "#8fe14b",
  "bg": "#0a120b",
  "line": "Begun in the Chapel of Sacred Mirrors, a meditation on Fear Inoculum.",
  "hpx": 2560
 },
 {
  "h": "tubular-20s-antique-radio-lamp",
  "t": "Echo",
  "title_html": "<em>Echo</em>",
  "kind": "Funktional Furniture",
  "colophon": "1920s radio &middot; stained-glass relic lamp",
  "price": 5500,
  "available": false,
  "url": "https://gavinger.com/products/tubular-20s-antique-radio-lamp",
  "img": "media/img/files__6FA08F48-CF8B-4253-8F51-602DE136644F.webp",
  "w": 1920,
  "cx": 0.5,
  "cy": 0.762,
  "size": 0.2,
  "accent": "#f0a63f",
  "bg": "#071512",
  "line": "A century-old radio reborn in stained glass, still listening for the signal.",
  "hpx": 2560
 }
];
